force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <description>Countries retrived using CountryLayer API</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Country__c/fields/Alpha2Code__c.field-meta.xml
<CustomField>
    <fullName>Alpha2Code__c</fullName>
    <description>Standardized two-letter country abbreviations defined by the International Organization for Standardization (ISO) to represent countries, dependent territories, and special geographic areas.</description>
    <externalId>true</externalId>
    <inlineHelpText>Two-letter country abbreviation.</inlineHelpText>
    <label>Alpha2Code</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Lead/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup relationship to the Country retrieved from CountryLayer, according with the Country from the Lead</description>
    <inlineHelpText>Country retrieved from CountryLayer</inlineHelpText>
    <label>Country</label>
    <referenceTo>Country__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/LeadCountryLayerService.cls
/**
 * Class with the logic to assign the Country__c lookup value depending if the Country field is filled
 * in Insert or Update the Lead and match Alpha2Code from an existing Country__c record
 */
public class LeadCountryLayerService {

    /**
     * Method to fill the Country__c lookup field with the Country__c record in case the CountryCode
     * has been changed from insert or update the Lead, and also it is found as Alpha2Code in Country__c records
    */
    public static void enrichLeadsWithCountry(List<Lead> newLeads, Map<Id, Lead> oldMap) 
    {
        List<Lead> leadsToProcess = new List<Lead>();

        //Filter the Leads without CountryCode to remove the relationship to Country__c
        for (Lead l : newLeads)
        {
            if (l.CountryCode == null) 
            {
                l.Country__c = null;
            }
            else 
            {
                leadsToProcess.add(l);    
            }
        }

        Set<String> alpha2Codes = getChangedCountryCodes(leadsToProcess, oldMap);
        
        if (alpha2Codes.isEmpty()) return;

        Map<String, Country__c> countryByCode = getCountriesByCodes(alpha2Codes);

        for (Lead l : leadsToProcess) 
        {
            // Only process with matching if the CountryCode is new or changed
            Boolean isNew     = (oldMap == null);
            Boolean isChanged = (!isNew && l.CountryCode != oldMap.get(l.Id)?.CountryCode);
            if (!isNew && !isChanged) continue;

            Country__c match = countryByCode.get(l.CountryCode.toUpperCase());
            l.Country__c = (match != null) ? match.Id : null;
        }
    }

    /**
     * Auxiliar method to retrieve the CountryCodes to be searched as Alpha2Code in Country__c records
     */
    private static Set<String> getChangedCountryCodes(List<Lead> newLeads, Map<Id, Lead> oldMap) 
    {
        Set<String> codes = new Set<String>();

        for (Lead l : newLeads) 
        {
            Boolean isNew     = (oldMap == null);
            Boolean isChanged = (!isNew && l.CountryCode != oldMap.get(l.Id)?.CountryCode);

            if (isNew || isChanged && !String.isBlank(l.CountryCode)) 
            {
                codes.add(l.CountryCode.toUpperCase());
            }
        }
        return codes;
    }

    /**
     * Auxiliar method to retrieve Country__c records with Alpha2Code if matches with CountryCode from Leads
     */
    private static Map<String, Country__c> getCountriesByCodes(Set<String> codes) 
    {
        Map<String, Country__c> result = new Map<String, Country__c>();
        
        for (Country__c c : [SELECT Id, Alpha2Code__c FROM Country__c WHERE Alpha2Code__c IN :codes]) 
        {
            result.put(c.Alpha2Code__c.toUpperCase(), c);
        }
        return result;
    }
}